CREATE DATABASE  IF NOT EXISTS `votw`;
USE `votw`;

DROP TABLE IF EXISTS `DocumentType`;

CREATE TABLE `DocumentType` (
`id` int(6) NOT NULL AUTO_INCREMENT,
 `name` varchar(45) Not NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



LOCK TABLES `DocumentType` WRITE;

UNLOCK TABLES;

